### PR TITLE
Update strings.xml (again)

### PR DESCRIPTION
**Pull request by TacoTheDank**
Meizu OS string is now correct

### CODE REVIEW

**Comment by abdulmalikkhan655** [comment]
becarefull guyz @TacoTheDank  is a scammer  so be careful

**Comment by TacoTheDank** [comment]
T_T why do you even bother, its honestly hilarious seeing you digging yourself deeper into that hole

**Comment by abdulmalikkhan655** [comment]
i know you are bug scammer i will show you here proof as soon as

**Comment by TacoTheDank** [comment]
k bud

**Pull request merged**
