### PR TITLE
Fixed error "Unknow error" on exec

### PR DESCRIPTION
**Pull request by Enyby**
See #202

### CODE REVIEW

**Comment by tiann** [comment]
Have you tested it ?

I tried my Nexus 5x Android 8.1 and android-emulator Android 7.0, it didn't reproduce.

**Comment by tiann** [comment]
@Enyby You should merge it to `exposed`,  `master` is deprecated.

I reverted this PR #204 , and could you open a new one?

**Comment by Enyby** [comment]
I tested it. Bug appear if buffer not flushed. Maybe it kernel related issue. But it too often error for GameGuardian users. And now, finally, after two days of research I am able fix it.

I open new pull request. Maybe you need remove branch master if it old?
#205

**Comment by tiann** [comment]
Thank you very much!

I will make exposed the master branch.

**Comment by tiann** [comment]
The branch has been renamed to master.

**Comment by tiann** [comment]
I am sorry, i have revert the default branch to `exposed`, rename branch seems making my commit history in a mess.

**Pull request merged**
