### PR TITLE
Updated en (English) translation

### PR DESCRIPTION
**Pull request by TacoTheDank**
Commit made via [Stringlate](https://lonamiwebs.github.io/stringlate/)

### CODE REVIEW

**Comment by TacoTheDank** [comment]
i dun goofed

**Comment by abdulmalikkhan655** [comment]
becare full guyz @TacoTheDank  is a scammer  so becareful

**Comment by TacoTheDank** [comment]
show me one fucking slice of evidence that i have done any such thing

**Comment by abdulmalikkhan655** [comment]
i will show you here proof

**Comment by abdulmalikkhan655** [comment]
i will fucking you

**Comment by abdulmalikkhan655** [comment]
you luck like my dick

**Comment by abdulmalikkhan655** [comment]
asshole

**Comment by TacoTheDank** [comment]
nice proof, really shows how mature you are 😂

**Pull request closed without merging**
